name: nekotomatatabi
description: ねことまた旅 - 猫と一緒に旅した気分で思い出を残す旅行記録アプリ
publish_to: 'none'
version: 0.11.1+12

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.2
  camera_windows: ^0.2.6+5
  geolocator: ^14.0.2
  http: ^1.5.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  image: ^4.5.4
  path: ^1.9.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  gal: ^2.3.3
  audioplayers: ^6.5.1
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home/
    - assets/bgm/
    - assets/camera_stamps/
    - assets/local_items/北海道地方/北海道/
    - assets/local_items/東北地方/青森/
    - assets/local_items/東北地方/岩手/
    - assets/local_items/東北地方/宮城/
    - assets/local_items/東北地方/秋田/
    - assets/local_items/東北地方/山形/
    - assets/local_items/東北地方/福島/
    - assets/local_items/関東地方/茨城/
    - assets/local_items/関東地方/栃木/
    - assets/local_items/関東地方/群馬/
    - assets/local_items/関東地方/埼玉/
    - assets/local_items/関東地方/千葉/
    - assets/local_items/関東地方/東京/
    - assets/local_items/関東地方/神奈川/
    - assets/local_items/中部地方/新潟/
    - assets/local_items/中部地方/富山/
    - assets/local_items/中部地方/石川/
    - assets/local_items/中部地方/福井/
    - assets/local_items/中部地方/山梨/
    - assets/local_items/中部地方/長野/
    - assets/local_items/中部地方/岐阜/
    - assets/local_items/中部地方/静岡/
    - assets/local_items/中部地方/愛知/
    - assets/local_items/近畿/三重/
    - assets/local_items/近畿/滋賀/
    - assets/local_items/近畿/京都/
    - assets/local_items/近畿/大阪/
    - assets/local_items/近畿/兵庫/
    - assets/local_items/近畿/奈良/
    - assets/local_items/近畿/和歌山/
    - assets/local_items/中国・四国/鳥取/
    - assets/local_items/中国・四国/島根/
    - assets/local_items/中国・四国/岡山/
    - assets/local_items/中国・四国/広島/
    - assets/local_items/中国・四国/山口/
    - assets/local_items/中国・四国/徳島/
    - assets/local_items/中国・四国/香川/
    - assets/local_items/中国・四国/愛媛/
    - assets/local_items/中国・四国/高知/
    - assets/local_items/九州/福岡/
    - assets/local_items/九州/佐賀/
    - assets/local_items/九州/長崎/
    - assets/local_items/九州/熊本/
    - assets/local_items/九州/大分/
    - assets/local_items/九州/宮崎/
    - assets/local_items/九州/鹿児島/
    - assets/local_items/九州/沖縄/
    - assets/icon/app_icon.png
