name: nekotomatatabi
description: ねことまた旅 - 猫と一緒に旅した気分で思い出を残す旅行記録アプリ
publish_to: 'none'
version: 0.9.0+9

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.2
  camera_windows: ^0.2.6+5
  geolocator: ^14.0.2
  http: ^1.5.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  image: ^4.5.4
  path: ^1.9.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  gal: ^2.3.3
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home/
    - assets/bgm/
    - assets/local_items/北海道地方/北海道/
    - assets/local_items/東北地方/青森県/
    - assets/local_items/東北地方/岩手県/
    - assets/local_items/東北地方/宮城県/
    - assets/local_items/東北地方/秋田県/
    - assets/local_items/東北地方/山形/
    - assets/local_items/東北地方/福島/
    - assets/local_items/関東地方/茨城/
    - assets/local_items/関東地方/栃木/
    - assets/local_items/関東地方/群馬/
    - assets/local_items/関東地方/埼玉/
    - assets/local_items/関東地方/千葉/
    - assets/local_items/関東地方/東京/
    - assets/local_items/関東地方/神奈川/
    - assets/local_items/中部地方/新潟/
    - assets/local_items/中部地方/富山/
    - assets/local_items/中部地方/石川/
    - assets/local_items/中部地方/福井/
    - assets/local_items/中部地方/山梨/
    - assets/local_items/中部地方/長野/
    - assets/local_items/中部地方/岐阜/
    - assets/local_items/中部地方/静岡/
    - assets/local_items/中部地方/愛知/
    - assets/icon/app_icon.png
